# GENERATED FILE. Use with Kubernetes 1.9+
# TO UPDATE, modify files in install/kubernetes/templates and run install/updateVersion.sh
apiVersion: v1
kind: Secret
metadata:
  name: mgwsecret
type: Opaque
data:
  mgorg: ${EDGEMICRO_ORG}
  mgenv: ${EDGEMICRO_ENV}
  mgkey: ${EDGEMICRO_KEY}
  mgsecret: ${EDGEMICRO_SECRET}
  mgconfig: ${EDGEMICRO_CONFIG}
---
kind: ConfigMap
metadata:
  name: edgemicro-inject
  namespace: edgemicro-system
apiVersion: v1
data:
  config: |
    policy: enabled
    template: |-
      initContainers:
      - name: edgemicro-init
        image: docker.io/edgemicrok8/edgemicro_proxy_init:latest
        args:
        - "-p"
        - 8000
        - "-u"
        - 1001
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        restartPolicy: Always
        imagePullPolicy: Always
      containers:
      - name: edge-microgateway
        image: docker.io/edgemicrok8/microgateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: EDGEMICRO_ORG
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgorg
        - name: EDGEMICRO_ENV
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgenv
        - name: EDGEMICRO_KEY
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgkey
        - name: EDGEMICRO_SECRET
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgsecret
        - name: EDGEMICRO_CONFIG
          valueFrom:
            secretKeyRef:
              name: mgwsecret
              key: mgconfig
        - name: EDGEMICRO_CONFIG_DIR
          value: /opt/apigee/.edgemicro
        - name: EDGEMICRO_DECORATOR
          value: 1
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: edgemicro-proxy
      - name: edgemicro-certs
        secret:
          optional: true
          {{ if eq .Spec.ServiceAccountName "" -}}
          secretName: edgemicro.default
          {{ else -}}
          secretName: {{ printf "edgemicro.%s" .Spec.ServiceAccountName }}
          {{ end -}}
